site_name: BioAWS
site_url: http://www.bioaws.com/
pages:
  - 首页: index.md
  - 文章:
    - 10分钟打造云上集群: blogs/2019-12-27-10-mins-to-create-a-cluster-on-aws.md
    - 构建基于AWS Batch的WDL服务: blogs/2020-01-06-wdl-and-cromwell-on-aws-batch-china.md
  - 关于此站: about.md
