site_name: BioAWS
site_url: https://davischen99.github.io/aws/
pages:
  - 首页: index.md
  - 文章:
    - 10分钟打造云上集群: blogs/2019-12-27-10-mins-to-create-a-cluster-on-aws.md
    - 构建基于AWS Batch的WDL服务: blogs/2020-01-06-wdl-and-cromwell-on-aws-batch-china.md
    - 2020的最后一天: blogs/2020-12-31-final-day-of-2020.md
  - 关于此站: about.md
